name: Go

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - uses: actions/checkout@v2
      - name: Run Unit tests
        run: go test -v -coverprofile=profile.cov ./...

      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=profile.cov -service=github

  semantic-release:
    needs: [test]
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Run semantic-release
        if: github.repository == 'casbin/redis-adapter' && github.event_name == 'push'
        run: |
          npm install --save-dev semantic-release@17.2.4
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}